import Head from 'next/head'
import Navigation from '../Components/Navigation'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="heroSection" className="hero-section">
        <div className="parallax"></div>
        <div className="overlay"></div>
        <Navigation />
        <div className="hero-cta">
          <h1>Ember House</h1>
          <a href="/reservation.html">Book a Reservation</a>
        </div>
      </section>

    </>
  )
}
